# CloudFormation template to deploy EC2 frontend and backend instances with a shared security group,
# Elastic IPs, and CloudWatch alarms for monitoring CPU usage, network traffic, disk I/O, and instance health.

AWSTemplateFormatVersion: '2010-09-09'

Resources:
  # Shared Security Group allowing common traffic for frontend and backend
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for frontend and backend instances
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22  # SSH access
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80  # HTTP access
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443  # HTTPS access
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306  # MySQL access (backend DB)
          ToPort: 3306
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1  # Allow all outbound traffic
          CidrIp: 0.0.0.0/0

  # Frontend EC2 instance
  FrontendInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-091f18e98bc129c4e
      KeyName: Sax-Admin-Key-001
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      IamInstanceProfile: EC2S3AccessRole
      Tags:
        - Key: Name
          Value: frontend-webserver

  # Backend EC2 instance
  BackendInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-091f18e98bc129c4e
      KeyName: Sax-Admin-Key-001
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      IamInstanceProfile: EC2S3AccessRole
      Tags:
        - Key: Name
          Value: backend-db

  # Associate static Elastic IP to frontend instance
  FrontendElasticIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref FrontendInstance
      AllocationId: eipalloc-046e45f42eb8fbad0

  # Associate static Elastic IP to backend instance
  BackendElasticIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref BackendInstance
      AllocationId: eipalloc-08a161070cb99fad0

  ### CloudWatch Alarms for FrontendInstance

  # Alarm: CPU usage exceeds 80%
  CPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "CPU usage exceeds 80%"
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Dimensions:
        - Name: InstanceId
          Value: !Ref FrontendInstance
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: []
      TreatMissingData: notBreaching

  # Alarm: NetworkOut exceeds 500MB over 5 minutes
  NetworkOutAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "NetworkOut exceeds 500MB"
      Namespace: AWS/EC2
      MetricName: NetworkOut
      Dimensions:
        - Name: InstanceId
          Value: !Ref FrontendInstance
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 524288000
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: []
      TreatMissingData: notBreaching

  # Alarm: Write operations as a proxy for high disk I/O
  DiskUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "VolumeWriteOps as a proxy for high disk I/O"
      Namespace: AWS/EC2
      MetricName: VolumeWriteOps
      Dimensions:
        - Name: InstanceId
          Value: !Ref FrontendInstance
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1000
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: []
      TreatMissingData: notBreaching

  # Alarm: Instance health check failure
  StatusCheckAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "EC2 instance failed status check"
      Namespace: AWS/EC2
      MetricName: StatusCheckFailed
      Dimensions:
        - Name: InstanceId
          Value: !Ref FrontendInstance
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: []
      TreatMissingData: notBreaching

  ### CloudWatch Alarms for BackendInstance

  # Alarm: CPU usage exceeds 80%
  BackendCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Backend CPU usage exceeds 80%"
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Dimensions:
        - Name: InstanceId
          Value: !Ref BackendInstance
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: []
      TreatMissingData: notBreaching

  # Alarm: NetworkOut exceeds 500MB over 5 minutes
  BackendNetworkOutAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Backend NetworkOut exceeds 500MB"
      Namespace: AWS/EC2
      MetricName: NetworkOut
      Dimensions:
        - Name: InstanceId
          Value: !Ref BackendInstance
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 524288000
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: []
      TreatMissingData: notBreaching

  # Alarm: Write operations as a proxy for high disk I/O
  BackendDiskUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Backend VolumeWriteOps as a proxy for high disk I/O"
      Namespace: AWS/EC2
      MetricName: VolumeWriteOps
      Dimensions:
        - Name: InstanceId
          Value: !Ref BackendInstance
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1000
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: []
      TreatMissingData: notBreaching

  # Alarm: Instance health check failure
  BackendStatusCheckAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Backend EC2 instance failed status check"
      Namespace: AWS/EC2
      MetricName: StatusCheckFailed
      Dimensions:
        - Name: InstanceId
          Value: !Ref BackendInstance
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: []
      TreatMissingData: notBreaching

Outputs:
  FrontendInstanceId:
    Description: Instance ID of the frontend web server
    Value: !Ref FrontendInstance

  BackendInstanceId:
    Description: Instance ID of the backend database server
    Value: !Ref BackendInstance
